server: 
 port: 8030
 
  
eureka: 
 instance:
  hostname: localhost
 
spring: 
  application: 
   name: api-gateway
  cloud: 
   gateway: 
    routes: 
     - id: Account-Details
       uri: lb://ACCOUNTDETAILS 
       predicates: 
        - Path=/ad/**
     - id: Fund-Transfer
       uri: lb://FUNDTRANSFER 
       predicates: 
        - Path=/ft/**
       